artifact_uri: file:///C:/Users/Usuario/Desktop/ProyectosPropios/fraudDetection/fraudDetection/fraudDetection/tracking/118694022652404248/b5444c2ab5114dfba1d21fd584dc3ea6/artifacts
end_time: 1756370243558
entry_point_name: ''
experiment_id: '118694022652404248'
lifecycle_stage: active
run_id: b5444c2ab5114dfba1d21fd584dc3ea6
run_name: rf_baseline_balanced
source_name: ''
source_type: 4
source_version: ''
start_time: 1756370158278
status: 3
tags: []
user_id: Usuario
