artifact_location: file:///C:/Users/Usuario/Desktop/ProyectosPropios/fraudDetection/fraudDetection/fraudDetection/tracking/118694022652404248
creation_time: 1756370156511
experiment_id: '118694022652404248'
last_update_time: 1756370156511
lifecycle_stage: active
name: creditcard_fraud_rf
