artifact_uri: file:///C:/Users/Usuario/Desktop/ProyectosPropios/fraudDetection/fraudDetection/fraudDetection/tracking/118694022652404248/04df86b4177e4ecbadf8089743dca536/artifacts
end_time: 1756394889089
entry_point_name: ''
experiment_id: '118694022652404248'
lifecycle_stage: active
run_id: 04df86b4177e4ecbadf8089743dca536
run_name: rf_baseline_balanced
source_name: ''
source_type: 4
source_version: ''
start_time: 1756394800664
status: 3
tags: []
user_id: Usuario
